// Schnellfragen der Projektintelligenz — Inhalte unverändert aus dem Panel ausgelagert.
export const QUICK_FRAGEN = [
  { label: 'Vollständige Projektanalyse', text: 'Führe die vollständige Einzelprojekt-Analyse für dieses Projekt durch — inklusive Kundenakt, Kommunikation und konkreter Empfehlung.' },
  { label: 'Was kann ich abrechnen?', text: 'Was kann bei diesem Projekt jetzt abgerechnet werden? Begründe mit Fortschritt, Budget, offenen verrechenbaren Stunden und den dokumentierten Vereinbarungen.' },
  { label: 'Risiken & Blockaden', text: 'Welche Risiken, Blockaden oder offenen Zusagen gibt es bei diesem Projekt?' },
  {
    label: 'Nachverrechnung prüfen (Mehrleistung)',
    text: 'Prüfe, ob bei diesem Projekt eine Nachverrechnung bzw. Mehrverrechnung gegenüber dem Kunden begründbar ist, und erstelle mir die vollständige Argumentationsgrundlage.\n\n1. IST-AUFWAND: Lade AworkProjectSnapshot und AworkTimeEntry zu diesem Projekt. Ermittle geplantes Zeitbudget (time_budget_minutes) gegen tatsächlich erfasste Zeit (tracked_duration_minutes / duration_minutes), in Stunden, sowie die Überschreitung in Stunden und Prozent. Ziehe die eigenen Zeitbuchungen (TimeEntry) dieses Projekts hinzu: Summe der Minuten, davon verrechenbar und nicht verrechenbar (mit nicht_verrechenbar_grund), sowie Buchungen mit ueber_kontingent = true. Zeige die größten Zeitfresser nach Aufgabe und nach Tätigkeit (TimeEntry.taetigkeit), sowie wer die Zeit gebucht hat.\n\n2. SOLL-LEISTUNG: Lade ConfirmedOrder und ConfirmedOrderItem sowie ProjectBillingBlock. Stelle dar, was ursprünglich beauftragt war (Positionen, Beträge netto) und welcher Betrag laut InvoiceRecord bereits fakturiert und bezahlt ist.\n\n3. MEHRLEISTUNG BELEGEN: Vergleiche den erbrachten Leistungsumfang mit dem Auftragsumfang. Nutze dazu den digitalen Kundenakt (ProjectFileEntry) sowie die Projektkommunikation: welche zusätzlichen Wünsche, Änderungen, Zusatzrunden oder Erweiterungen sind belegt? Führe jede Mehrleistung mit Belegstelle (Datum, Quelle, Zitat) an. Unterscheide klar: (a) belegte Zusatzwünsche des Kunden — verrechenbar, (b) interne Ineffizienz oder Nachbesserung — nicht verrechenbar, (c) unklar — Rückfrage nötig. Achte auf dokumentierte Vereinbarungen wie Pauschalen oder Deckelungen, die eine Nachverrechnung ausschließen — diese haben Vorrang.\n\n4. VORSCHLAG: Berechne den nachverrechenbaren Betrag netto auf Basis der verrechenbaren Mehrstunden und eines plausiblen Stundensatzes (nenne den angesetzten Satz und woher er kommt). Gib eine Bandbreite an: konservativ / realistisch / maximal, jeweils mit Begründung.\n\n5. KUNDENANSPRACHE: Formuliere einen fertigen, sachlichen E-Mail-Text an den Kunden auf Deutsch (Sie-Form, österreichischer Ton, wertschätzend, ohne Vorwurf): kurzer Rückblick auf den Projektverlauf, konkrete Auflistung der Zusatzleistungen, transparente Stunden- und Betragsdarstellung, klarer Vorschlag zur Nachverrechnung und Frage nach Freigabe.\n\n6. RISIKO: Nenne abschließend die Gegenargumente, die der Kunde bringen könnte, und wie wir darauf antworten. Wenn die Datenlage für eine Nachverrechnung nicht ausreicht, sage das klar und nenne, welche Belege fehlen.',
  },
];