// Navigationsziele der Anwendung — Quelle für die Sprungziele der Suche.
export const NAV_TARGETS = [
  { path: '/freigaben', label: 'Freigaben', area: 'management' },
  { path: '/dashboard', label: 'Finanz-Dashboard', area: 'management' },
  { path: '/projects', label: 'Projekt-Cockpit', area: 'projects' },
  { path: '/next-month-forecast', label: 'Abrechnungsforecast', area: 'backoffice' },
  { path: '/invoice-ready', label: 'Abrechnungsanweisungen', area: 'backoffice' },
  { path: '/support-billing', label: 'Support-Abrechnung', area: 'backoffice' },
  { path: '/customer-risk', label: 'Kundenrisiko', area: 'management' },
  { path: '/awork-cost-index', label: 'awork Kostenindex', area: 'management' },
  { path: '/escalation-alerts', label: 'Projekt-Risiko', area: 'management' },
  { path: '/crm', label: 'CRM Pipeline', area: 'sales' },
  { path: '/crm/inbox', label: 'Posteingang', area: 'sales' },
  { path: '/crm/emails', label: 'E-Mail-Zentrale', area: 'sales' },
  { path: '/crm/escalations', label: 'Kunden-Eskalationen', area: 'sales' },
  { path: '/crm/proposals', label: 'Angebots-Studio', area: 'sales' },
  { path: '/sprint/uebersicht', label: 'Wochenübersicht', area: 'projects' },
  { path: '/sprint', label: 'Mein Tag', area: 'projects' },
  { path: '/zeiten', label: 'Zeiten', area: 'projects' },
  { path: '/sprint/projekte', label: 'Projekte', area: 'projects' },
  { path: '/sprint/intelligence', label: 'Projekt-Intelligence', area: 'intelligence' },
  { path: '/sprint/planung', label: 'Wochenplanung', area: 'projects' },
  { path: '/sprint/steuerung', label: 'Steuerung', area: 'management' },
  { path: '/cashflow-advisor', label: 'KI-Finanzanalyse', area: 'intelligence' },
  { path: '/weekly-cashflow', label: 'Wöchentlicher Cashflow', area: 'management' },
  { path: '/variance-analysis', label: 'Abweichungsanalyse', area: 'management' },
  { path: '/forecast', label: 'Forecast & Szenarien', area: 'management' },
  { path: '/receivables', label: 'Offene Forderungen', area: 'backoffice' },
  { path: '/confirmed-orders', label: 'Auftragsabwicklung', area: 'backoffice' },
  { path: '/online-marketing', label: 'Online-Marketing', area: 'backoffice' },
  { path: '/maintenance', label: 'Wartungsverträge', area: 'backoffice' },
  { path: '/hosting', label: 'Hosting & Domains', area: 'backoffice' },
  { path: '/production', label: 'Planumsatz Produktion', area: 'management' },
  { path: '/tools', label: 'Toolkosten', area: 'backoffice' },
  { path: '/payables', label: 'Eingangsrechnungen', area: 'backoffice' },
  { path: '/revenue-analysis', label: 'Umsatzbewertung', area: 'management' },
  { path: '/system/maintenance', label: 'Systempflege', area: 'management' },
];